apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-v1
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: v1
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: localhost/user-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_VERSION
          value: v1
        ports:
        - name: grpc
          containerPort: 50051

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-v2
  namespace: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: v2
  template:
    metadata:
      labels:
        app: user-service
        version: v2
    spec:
      containers:
      - name: user-service
        image: localhost/user-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_VERSION
          value: v2
        ports:
        - name: grpc
          containerPort: 50051

---


apiVersion: v1
kind: Service
metadata:
  name: user-service-v1
  labels:
    app.kubernetes.io/name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
    version: v1
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-v2
  labels:
    app.kubernetes.io/name: user-service
spec:
  type: ClusterIP
  selector:
    app: user-service
    version: v2
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
---

apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: app-demo
spec:
  ports:
  - name: grpc
    appProtocol: kubernetes.io/h2c
    port: 50051
    targetPort: grpc

---

apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: userservice-route
  namespace: app-demo
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: user-service
    port: 50051
  rules:
  - matches:
    - method:
        service: usercard.UserService
        method: GetUser
    backendRefs:
    - name: user-service-v1
      port: 50051
      weight: 50
    - name: user-service-v2
      port: 50051
      weight: 50
  - matches:
    - method:
        service: usercard.UserService
        method: CreateUser
    backendRefs:
    - name: user-service-v1
      port: 50051
      weight: 50
    - name: user-service-v2
      port: 50051
      weight: 50
  # DEFAULT
  - backendRefs:
    - name: user-service-v1
      port: 50051
      weight: 100
